### ISSUE TITLE
ERROR in training steps！

### ISSUE THREAD

**Issue by sunmooncode** [meituan/YOLOv6#536]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）  

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

训练命令: **python -m torch.distributed.launch --nproc_per_node 2 tools/train.py --batch-size 24 --conf-file configs/yolov6s_finetune.py --data-path data/dataset.yaml --device 0,1**
运行环境: ubuntu20.04
CUDA: 11.6

在训练三个epoch之后出现以下错误:
`Training start...

     Epoch  iou_loss  dfl_loss  cls_loss
     0/199    0.8503         0     3.092:   0%|          | 1/855 [00:01<21:48,  1.53s/it]                                                                                                                          Reducer buckets have been rebuilt in this iteration.
     0/199      0.49         0     1.559: 100%|██████████| 855/855 [03:41<00:00,  3.86it/s]                                                                                                                        
Inferencing model in train datasets.: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 66/66 [00:31<00:00,  2.11it/s]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp3/predictions.json...
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
DONE (t=1.73s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=5.56s).
Accumulating evaluation results...
DONE (t=2.46s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.503
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.697
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.572
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.216
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.445
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.510
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.388
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.726
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.762
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.616
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.767
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.828
Results saved to runs/train/exp3
Epoch: 0 | mAP@0.5: 0.6965942642081021 | mAP@0.50:0.95: 0.5034598777528265

     Epoch  iou_loss  dfl_loss  cls_loss
     1/199    0.4308         0     0.973: 100%|██████████| 855/855 [03:43<00:00,  3.82it/s]                                                                                                                        

     Epoch  iou_loss  dfl_loss  cls_loss
     2/199    0.4336         0      0.93: 100%|██████████| 855/855 [03:01<00:00,  4.70it/s]                                                                                                                        

     Epoch  iou_loss  dfl_loss  cls_loss
     3/199    0.4146         0    0.8787: 100%|█████████▉| 854/855 [03:32<00:00,  3.91it/s]                                                                                                                        ERROR in training steps.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main(args)
  File "tools/train.py", line 116, in main
    trainer.train()
  File "/home/ubuntu/YOLOv6/yolov6/core/engine.py", line 99, in train
    self.train_in_loop(self.epoch)
  File "/home/ubuntu/YOLOv6/yolov6/core/engine.py", line 113, in train_in_loop
    self.train_in_steps(epoch_num, self.step)
  File "/home/ubuntu/YOLOv6/yolov6/core/engine.py", line 134, in train_in_steps
    preds, s_featmaps = self.model(images)
  File "/home/ubuntu/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Killing subprocess 219302
Killing subprocess 219303
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/yolov6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/yolov6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/anaconda3/envs/yolov6/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/yolov6/bin/python', '-u', 'tools/train.py', '--local_rank=1', '--batch-size', '24', '--conf-file', 'configs/yolov6s_finetune.py', '--data-path', 'data/dataset.yaml', '--device', '0,1']' returned non-zero exit status 1.`

1.按照报错提示添加 **model = DDP(model, device_ids=[args.local_rank], output_device=args.local_rank, find_unused_parameters=True)** 依旧没有解决问题
2.在我按照pip install -r requirements.txt安装环境之后，无法使用推荐的训练命令训练。具体报错如下:
 `RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:46, unhandled cuda error, NCCL version 2.10.3
ncclUnhandledCudaError: Call to CUDA function failed.`

**Comment by shensheng272** [comment]
你好，请问使用的pytorch版本是多少？
另外是在公开数据集上进行的实验的吗？

**Comment by sunmooncode** [comment]
@sunmooncode 错误1的pytorch版本是[https://github.com/ultralytics/yolov5/issues/4530](url)按照这个安装的
                           错误2是最新版的1.12.1，但是安装其他版本的pytorch也无法正常训练

**Comment by sunmooncode** [comment]
@shensheng272 第一个问题我已经解决了 好像是数据中含有背景数据导致的，我去掉背景数据之后问题就没有了。

**Comment by mtjhl** [comment]
第二个问题，您跑其他的算法， 用DDP 模式，可以正常运行吗？

**Comment by sunmooncode** [comment]
@mtjhl **python -m torch.distributed.launch --nproc_per_node 2 train.py --batch 24 --data data/coco128.yaml  --device 0,1 --weights weights/yolov5s.pt**这是yolov5的训练命令，系统环境一样，torch==1.12.1，可以正常训练。

**Comment by Chilicyy** [comment]
@sunmooncode 问题二是因为安装的torch版本跟cuda版本不对应导致的，因为用户的机器我们无法预知，只能提供必要的库及版本信息，用户可根据自己的机器环境安装对应的库。一般来说，可以运行Yolov5的环境可以正常运行Yolov6。
第一个问题看您这边已经解决了，请问下数据中含有背景数据指的是什么数据？可以具体描述下吗？

**Comment by sunmooncode** [comment]
@Chilicyy 背景数据就是不含有任何类别的图片，没有对应的标签文件！

**Comment by lyp19921126** [comment]
> 第二个问题，您跑其他的算法， 用DDP 模式，可以正常运行吗？ @sunmooncode



> 第二个问题，您跑其他的算法， 用DDP 模式，可以正常运行吗？ @sunmooncode

数据集中允许存在只有背景的数据吗？
