### ISSUE TITLE
ERROR in training loop or eval/save model

### ISSUE THREAD

**Issue by tms2003** [meituan/YOLOv6#566]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

在训练自己的数据集中出现了以下错误。注意：它不是一开始就出错，而是经过3个epoch后出错。
```
../aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [130,0,0], thread: [91,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [130,0,0], thread: [92,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [130,0,0], thread: [93,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [130,0,0], thread: [94,0,0] Assertion `input_val >= zero && input_val <= one` failed.
../aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [130,0,0], thread: [95,0,0] Assertion `input_val >= zero && input_val <= one` failed.
     3/399    0.2844    0.1872       inf:  91%|█████████ | 40/44 [00:18<00:01,  2.22it/s]                                                                                                                          
ERROR in training steps.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main(args)
  File "tools/train.py", line 116, in main
    trainer.train()
  File "/home/incar/tms/source/YOLOv6/yolov6/core/engine.py", line 99, in train
    self.train_in_loop(self.epoch)
  File "/home/incar/tms/source/YOLOv6/yolov6/core/engine.py", line 113, in train_in_loop
    self.train_in_steps(epoch_num, self.step)
  File "/home/incar/tms/source/YOLOv6/yolov6/core/engine.py", line 142, in train_in_steps
    total_loss, loss_items = self.compute_loss(preds, targets, epoch_num, step_num)
  File "/home/incar/tms/source/YOLOv6/yolov6/models/loss.py", line 161, in __call__
    loss_iou, loss_dfl = self.bbox_loss(pred_distri, pred_bboxes, anchor_points_s, target_bboxes,
  File "/home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/incar/tms/source/YOLOv6/yolov6/models/loss.py", line 216, in forward
    if num_pos > 0:
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from record at ../aten/src/ATen/cuda/CUDAEvent.h:119 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fc6c7d127d2 in /home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x267da25 (0x7fc71ad31a25 in /home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #2: <unknown function> + 0x300568 (0x7fc77d12a568 in /home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: c10::TensorImpl::release_resources() + 0x175 (0x7fc6c7cfb005 in /home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x1ee569 (0x7fc77d018569 in /home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x4d9c78 (0x7fc77d303c78 in /home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x292 (0x7fc77d303f72 in /home/incar/miniconda3/envs/py3.8/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #19: __libc_start_main + 0xf3 (0x7fc77f9f8083 in /lib/x86_64-linux-gnu/libc.so.6)

已放弃 (核心已转储)
```

这是我的训练命令：
 python tools/train.py --batch 24  --conf configs/yolov6l_finetune.py --data data/drone.yaml --device 0
请问是为什么？

**Comment by mtjhl** [comment]
收到，我们在定位分析这个问题。修复后即刻回复您。

**Comment by Chilicyy** [comment]
您好，请问您有使用预训练权重吗？

**Comment by tms2003** [comment]
@Chilicyy 有使用。但可能我的训练内容与预训练权重差别大。

**Comment by Chilicyy** [comment]
您可以尝试将学习率调低一些看是否正常。

**Comment by tms2003** [comment]
@Chilicyy 我有空再试一试。主要是这个数据集在v5/v7上都可以。v7一开始mAP非常低,但总不至于不能保存。后面就升上去了。

**Comment by kb401cyj** [comment]
你好，想请问一下这个问题是怎样解决的还记得吗

**Comment by knoppmyth** [comment]
@kb401cyj I got this error as well. In mine case, the error was occurring during eval and related to pycocotools. I look at the version that was install and it was pycocotools 2.0.10. I installed 2.0.8 and it resolved the issue for me.
