### ISSUE TITLE
训练过程中 跑到第三轮就断了 报如下错误

### ISSUE THREAD

**Issue by Wang-cell1999** [meituan/YOLOv6#587]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

2张3090TI 跑到第三轮就报错 我看释放内存了 
parser = argparse.ArgumentParser(description='YOLOv6 PyTorch Training', add_help=add_help)
    parser.add_argument('--data-path', default='mydataset.yaml', type=str, help='path of dataset')
    parser.add_argument('--conf-file', default='./configs/yolov6s.py', type=str, help='experiments description file')
    parser.add_argument('--img-size', default=640, type=int, help='train, val image size (pixels)')
    parser.add_argument('--batch-size', default=8, type=int, help='total batch size for all GPUs')
    parser.add_argument('--epochs', default=100, type=int, help='number of total epochs to run')
    parser.add_argument('--workers', default=8, type=int, help='number of data loading workers (default: 8)')
。。。
ERROR in training steps.
ERROR in training loop or eval/save model.
OOM RuntimeError is raised due to the huge memory cost during label assignment.                                                                                              CPU mode is applied in this batch. If you want to avoid this issue,                                                                                              try to reduce the batch size or image size.
Traceback (most recent call last):
  File "/data0/wsd/YOLOv6-main/yolov6/models/loss.py", line 95, in __call__
    mask_gt)
  File "/home/xmsh/software/anaconda3/envs/torch37/lib/python3.7/site-packages/torch/nn/mo                                                                         dules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xmsh/software/anaconda3/envs/torch37/lib/python3.7/site-packages/torch/autog                                                                         rad/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data0/wsd/YOLOv6-main/yolov6/assigners/tal_assigner.py", line 57, in forward
    pd_scores, pd_bboxes, gt_labels, gt_bboxes, anc_points, mask_gt)
  File "/data0/wsd/YOLOv6-main/yolov6/assigners/tal_assigner.py", line 84, in get_pos_mask
    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bbox                                                                         es)
  File "/data0/wsd/YOLOv6-main/yolov6/assigners/tal_assigner.py", line 108, in get_box_met                                                                         rics
    overlaps = iou_calculator(gt_bboxes, pd_bboxes)
  File "/data0/wsd/YOLOv6-main/yolov6/assigners/assigner_utils.py", line 84, in iou_calcul                                                                         ator
    overlap = (x2y2 - x1y1).clip(0).prod(-1)
RuntimeError: CUDA driver error: device-side assert triggered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data0/wsd/YOLOv6-main/yolov6/core/engine.py", line 99, in train
    self.train_in_loop(self.epoch)
  File "/data0/wsd/YOLOv6-main/yolov6/core/engine.py", line 113, in train_in_loop
    self.train_in_steps(epoch_num, self.step)
  File "/data0/wsd/YOLOv6-main/yolov6/core/engine.py", line 142, in train_in_steps
    total_loss, loss_items = self.compute_loss(preds, targets, epoch_num, step_num)
  File "/data0/wsd/YOLOv6-main/yolov6/models/loss.py", line 103, in __call__
    torch.cuda.empty_cache()
  File "/home/xmsh/software/anaconda3/envs/torch37/lib/python3.7/site-packages/torch/cuda/                                                                         memory.py", line 121, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktra                                                                         ce below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 130, in <module>
    main(args)
  File "train.py", line 120, in main
    trainer.train()
  File "/data0/wsd/YOLOv6-main/yolov6/core/engine.py", line 106, in train
    self.train_after_loop()
  File "/data0/wsd/YOLOv6-main/yolov6/core/engine.py", line 297, in train_after_loop
    torch.cuda.empty_cache()
  File "/home/xmsh/software/anaconda3/envs/torch37/lib/python3.7/site-packages/torch/cuda/                                                                         memory.py", line 121, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktra                                                                         ce below might be incorrect.

### Additional

![image](https://user-images.githubusercontent.com/75870013/199865942-8b42126e-d135-476f-8bf9-e4245d9b4539.png)
![image](https://user-images.githubusercontent.com/75870013/199866364-109c75c0-dae3-4870-acf7-51adfd4e0ac4.png)

**Comment by Chilicyy** [comment]
训练自定义数据集，建议用yolov6s_finetune.py配置文件。

**Comment by Wang-cell1999** [comment]
好，我试一下。微调是改参数了吗？

**Comment by Wang-cell1999** [comment]
> 好，我试一下。微调是改参数了吗？
我对比了一下 ，超参数变了

**Comment by Chilicyy** [comment]
是的，你可以对比看下。

**Comment by Wang-cell1999** [comment]
不行呀，up还是跑三轮断了。我的 数据集大概有5w张图片，dataset只有一类  有关系吗 ？需要额外设置什么参数吗？
![image](https://user-images.githubusercontent.com/75870013/199905729-5246e663-6b62-4f85-85f3-dcd017f657d8.png)
![image](https://user-images.githubusercontent.com/75870013/199905803-78892b07-d543-4a85-bdc2-a7c0970c338e.png)
![image](https://user-images.githubusercontent.com/75870013/199905850-e3c86307-c7d3-4a50-9e12-c7d05c528b99.png)

**Comment by Chilicyy** [comment]
训练启动命令麻烦发下，有用ddp模式吗？另外，这边采用的是什么时候拉取的代码？

**Comment by Wang-cell1999** [comment]
没有用到ddp模式，我用的pycharm连接的服务器。10月26号拉取得代码。
train.py配置的：
![image](https://user-images.githubusercontent.com/75870013/199907587-3c7111d0-e654-4e51-bc2e-93e5ea1a7bb4.png)
mydataset.py如下：
![image](https://user-images.githubusercontent.com/75870013/199907668-fc43379a-5d0c-4b14-b45a-1f3c9d42e475.png)

**Comment by Chilicyy** [comment]
这边可以网上搜索下pycharm上运行pytorch分布式训练的配置。另外，麻烦运行时查看下显存占用量是否超了。

**Comment by luoshenhua1** [comment]
兄弟，遇到同样的问题了，困两天了，解决了吗，我重新配置环境也不行

**Comment by Wang-cell1999** [comment]
你是训练的1类吗？ 我类别之前是1类 ，改成了2【persion，other】

**Comment by luoshenhua1** [comment]
没，我训练6类

**Comment by luoshenhua1** [comment]
最后在重新下载下代码试一下，不行就就拿其它的作对比试验了

**Comment by Wang-cell1999** [comment]
感觉很离谱，前面三轮可以跑，第四轮报错。
可能是显存炸了。感觉还是看看v5把。解决了 给我说qwq

**Comment by Wang-cell1999** [comment]
我用的3090TI 感觉batchsize设成8 很不合理 有时候8可以 有时候就错了 太难了

**Comment by luoshenhua1** [comment]
v5，v7使用都可顺畅了

**Comment by Wang-cell1999** [comment]
v7看着v5演变的，v6看着yolox。同学v5，v7改进啥了 添加注意力好使吗？

**Comment by luoshenhua1** [comment]
只添加注意力不太够，可以加点别的

**Comment by Wang-cell1999** [comment]
还有啥可以加的吗 ？ FPN？ 求指点

**Comment by luoshenhua1** [comment]
还在尝试阶段，老师跟我说加一个注意力不太够

**Comment by Wang-cell1999** [comment]
真实 ，我们最近开题，我快愁死了 代码也不会改

**Comment by all-for-code** [comment]
@Chilicyy 请问这个问题已经解决了，为什么我拉取最新的代码依然有这个问题？
