### ISSUE TITLE
Assertion `target_val >= zero && target_val <= one` failed.

### ISSUE THREAD

**Issue by debugmenot** [meituan/YOLOv6#966]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

Hi! Randomly getting this error when training on custom dataset. Config: yolov6n_finetune.py, with (use_dfl=True, reg_max=16). Training with dfl to do distillation later for use on RockChip NPU (rknn).

--resume helps to continue the training from last sucessfull epoch approximately up to 70-80 epoch, then restarting the training from last checkpoint does not helps.

Tried to train on single 3080Ti GPU (32 batch size) and on 2x3090 GPU (64 batch size). Got same issues.

Please help!

Log:

     Epoch  iou_loss  dfl_loss  cls_loss
    11/299    0.4117    0.3526     1.057:  96%|█████████▌| 1244/1301 [03:23<00:08,  6.56it/s]       ../aten/src/ATen/native/cuda/Loss.cu:95: operator(): block: [1769,0,0], thread: [54,0,0] Assertion `target_val >= zero && target_val <= one` failed.
    11/299    0.4117    0.3526     1.057:  96%|█████████▌| 1244/1301 [03:23<00:09,  6.10it/s]
ERROR in training steps.
ERROR in training loop or eval/save model.
Traceback (most recent call last):
  File "/home/badcode/NEW2/YOLOv6/yolov6/core/engine.py", line 109, in train
    self.train_in_loop(self.epoch)
  File "/home/badcode/NEW2/YOLOv6/yolov6/core/engine.py", line 123, in train_in_loop
    self.train_in_steps(epoch_num, self.step)
  File "/home/badcode/NEW2/YOLOv6/yolov6/core/engine.py", line 154, in train_in_steps
    total_loss_ab, loss_items_ab = self.compute_loss_ab(preds[:3], targets, epoch_num, step_num) # YOLOv6_ab
  File "/home/badcode/NEW2/YOLOv6/yolov6/models/losses/loss_fuseab.py", line 131, in __call__
    if target_scores_sum > 0:
RuntimeError: CUDA error: device-side assert triggered

**Comment by Chilicyy** [comment]
@debugmenot Hi, are you using the lastest code from main branch?  If not, please git pull the lastest code and try again with a smaller batchsize (learning_rate would be automatically adjusted following the batchsize and gpu nums that you set.)

**Comment by Chilicyy** [comment]
@debugmenot Hi, we have fixed the dataloader bug when not using ram-cache. As for the NaNs tensor problem, how's it going on by adding sigmoid to BCE loss. Besides, are you using ddp mode for training with 2 gpus?

**Comment by dizzyd** [comment]
@debugmenot - how did you determine the images were broken? I'm seeing this same issue...

**Comment by debugmenot** [comment]
@dizzyd use pytorch version 1.*

**Comment by pantment** [comment]
@dizzyd  Can you explain how you address this issue? I have the same issue

**Comment by dizzyd** [comment]
@pantment - as @debugmenot noted, you should downgrade to pytorch 1.* and this bug goes away. Not entirely sure why, but it definitely helps.

**Comment by burak43** [comment]
For those that uses higher pytorch versions and there are no issues with the dataset labels, the following fixes this bug.

After the below line,
https://github.com/meituan/YOLOv6/blob/e86a483f3f6bded25d45970b56831345a99744a4/yolov6/assigners/tal_assigner.py#L81

Add:
`target_scores = torch.clamp(target_scores, 0, 1)`
